// Good Forgotten4 categories have ~6-20 plausible choices
export const narrowCards = [
  'Types of tree',
  'Movies with multiple sequels',
  'Breakfast foods',
  'Ice cream flavors',
  'Flowers',
  'Things in the kitchen',
  'Sandwiches',
  'School subjects',
  'Stones or gems',
  'Musical instruments',
  'Pizza toppings',
  'Fish',
  'Kinds of candy',
  'Footware',
  'Things that are sticky',
  'Cosmetics or toiletries',
  'Reptiles or amphibians',
  'Cooking utensils',
  'Allergens',
  'Fruits',
  'Weapons',
  'Things that use a remote',
  'Card games',
  'Foreign words used in English',
  'Things you sit in or on',
  'Titles people can have',
  'Things that have buttons',
  'Desserts',
  'Canned foods',
  'Things with stripes',
  'Olympic sports',
  'Pet species',
  'Languages',
  'Furniture',
  'Things in the bedroom',
  'Things you drive',
]

// Good 3Fold or 1:1 categories have 30+ plausible choices
export const wideCards = [
  'Gifts',
  'Beverages',
  'Toys',
  'Domestic cities',
  'Ocean things',
  'Nicknames',
  'Hobbies',
  'Parts of the body',
  'Politicians',
  'Things that jump or bounce',
  'Actors',
  'Things in a park',
  'Foreign cities',
  'Things in the sky',
  'Colleges or universities',
  'Countries',
  'Things that have spots',
  'Historical figures',
  'Drugs',
  'Fictional characters',
  'Menu items',
  'Capitals',
  'Items you save up to buy',
  'Something you keep hidden',
  'Items in a suitcase',
  'Things with tails',
  'Sports equipment',
  'Crimes',
  'Awards or ceremonies',
  'Cars',
  'Herbs or spices',
  'Bad habits',
  'Celebrities',
  'Parks',
  'Leisure activities',
  'Restaurants',
  'Notorious people',
  'Things in a medicine cabinet',
  'Household chores',
  'Bodies of water',
  'Authors',
  'Halloween costumes',
  'Things that are round',
  'Words associated with exercise',
  'Common names',
  'Rivers',
  'Mammals',
  'Things that are cold',
  'Insects',
  'TV shows',
  'Things that grow',
  'Things that are black',
  'Movies',
  'Birds',
  'Cartoon characters',
  'Holidays',
  'Things that are square',
  'Clothing',
  'Board games',
  'Video games',
  'Sports stars',
  'School supplies',
  'Things that are hot',
  'Heroes',
  'Fears',
  'Colors',
  'States or provinces',
  'Sports equipment',
  'Tools',
  'Electronic gadgets',
  'Internet lingo',
  'Computer parts',
  'Kinds of soup',
  "Things you shouldn't touch",
  'Spicy foods',
  'Things you make',
  'Things at a carnival',
  'Software',
  'Vacation spots',
  'Things that can kill you',
  'Words associated with winter',
  'Historical events',
  'Containers',
  'Types of weather',
  'Things that have wheels',
  'Farm animals',
  'Athletes',
  '4-letter words',
  'Street names',
  'Things at the beach',
  'Words associated with money',
  'Musicians',
  'Zoo animals',
  'Apps',
  'Workout moves',
  'Books',
  '3-letter words',
  'Occupation',
  'Name brand',
  'Villains',
  'Liquids',
  'Songs',
]

export const allCards = narrowCards.concat(wideCards)
