export const categories = [
  'Types of tree',
  'Muppets',
  'Movies with multiple sequels',
  'Breakfast foods',
  'Gifts',
  'Flowers',
  'Ice cream flavors',
  'Beverages',
  'Toys',
  'Domestic cities',
  'Things in the kitchen',
  'Ocean things',
  'Nicknames',
  'Hobbies',
  'Parts of the body',
  'Sandwiches',
  'Politicians',
  'School subjects',
  'Things that jump/bounce',
  'Actors',
  'Things in a park',
  'Foreign cities',
  'Stones/Gems',
  'Musical instruments',
  'Things in the sky',
  'Pizza toppings',
  'Colleges/Universities',
  'Fish',
  'Countries',
  'Things that have spots',
  'Historical figures',
  'Drugs',
  'Fictional characters',
  'Menu items',
  'Capitals',
  'Kinds of candy',
  'Items you save up to buy',
  'Footware',
  'Something you keep hidden',
  'Items in a suitcase',
  'Things with tails',
  'Sports equipment',
  'Crimes',
  'Things that are sticky',
  'Awards/ceremonies',
  'Cars',
  'Spices/herbs',
  'Bad habits',
  'Cosmetics/toiletries',
  'Celebreties',
  'Cooking utensils',
  'Reptiles/amphibians',
  'Parks',
  'Leisure activities',
  'Allergens',
  'Restaurants',
  'Notorious people',
  'Fruits',
  'Things in a medicine cabinet',
  'Household chores',
  'Bodies of water',
  'Authors',
  'Halloween costumes',
  'Weapons',
  'Things that are round',
  'Words associated with exercise',
  'Common names',
  'Rivers',
  'Mammals',
  'Things that are cold',
  'Insects',
  'TV shows',
  'Things that grow',
  'Things that are black',
  'Movies',
  'Birds',
  'Cartoon characters',
  'Holidays',
  'Things that are square',
  'Clothing',
  'Board games',
  'Video games',
  'Sports stars',
  'School supplies',
  'Things that are hot',
  'Heroes',
  'Fears',
  'Colors',
  'States/provinces',
  'Sports equipment',
  'Tools',
  'Electronic gadgets',
  'Things that use a remote',
  'Card games',
  'Internet lingo',
  'Computer parts',
  'Kinds of soup',
  'Foreign words use in English',
  "Things you shouldn't touch",
  'Spicy foods',
  'Things you make',
  'Things at a carnival',
  'Software',
  'Vacation spots',
  'Things that can kill you',
  'Words associated with winter',
  'Historical events',
  'Containers',
  'Things you sit in/on',
  'Types of weather',
  'Titles people can have',
  'Things that have buttons',
  'Things that have wheels',
  'Farm animals',
  'Athletes',
  '4-letter words',
  'Street names',
  'Things at the beach',
  'Desserts',
  'Words associated with money',
  'Musicians',
  'Zoo animals',
  'Canned foods',
  'Apps',
  'Things with stripes',
  'Sports',
  'Workout moves',
  'Pets',
  'Languages',
  'Books',
  '3-letter words',
  'Things you drive',
  'Occupation',
  'Name brand',
  'Villains',
  'Liquids',
  'Songs',
  'Furniture',
  'Things in the bedroom',
]
