export const axisCards = [
  // ['Good', 'Evil'],
  // ['Lawful', 'Chaotic'],
  // ['Fast', 'Slow'],
  // ['Strong', 'Weak'],
  // ['Big', 'Small'],
  // ['Science', 'Magic'],
  // ['Water', 'Fire'],
  // ['Loud', 'Quiet'],
  // ['Light', 'Dark'],
  // ['Cold', 'Hot'],
  // ['Expensive', 'Cheap'],
  // ['Old', 'New'],
  // ['Fun', 'Boring'],
  // ['High', 'Low'],
  // ['Funny', 'Serious'],
  ['blurry', 'sharp'],
  ['retro', 'futuristic'],
  ['sincere', 'phony'],
  ['inspiring', 'embarrassing'],
  ['liquid', 'solid'],
  ['electronic', 'analog'],
  ['yucky', 'yummy'],
  ['fragrant', 'smelly'],
  ['lost', 'found'],
  ['demon', 'angel'],
  ['bald', 'hairy'],
  ['cool', 'uncool'],
  ['artistic', 'scientific'],
  ['visible', 'invisible'],
  ['outsider', 'insider'],
  ['dull', 'sharp'],
  ['squishy', 'firm'],
  ['fast', 'slow'],
]
