export const axisCards = [
  // ['Good', 'Evil'],
  // ['Lawful', 'Chaotic'],
  // ['Fast', 'Slow'],
  // ['Strong', 'Weak'],
  // ['Big', 'Small'],
  // ['Science', 'Magic'],
  // ['Water', 'Fire'],
  // ['Loud', 'Quiet'],
  // ['Light', 'Dark'],
  // ['Cold', 'Hot'],
  // ['Expensive', 'Cheap'],
  // ['Old', 'New'],
  // ['Fun', 'Boring'],
  // ['High', 'Low'],
  // ['Funny', 'Serious'],
  ['blurry', 'sharp'],
  ['retro', 'futuristic'],
  ['sincere', 'phony'],
  ['inspiring', 'embarrassing'],
  ['liquid', 'solid'],
  ['electronic', 'analog'],
  ['yucky', 'yummy'],
  ['fragrant', 'smelly'],
  ['lost', 'found'],
  ['demon', 'angel'],
  ['bald', 'hairy'],
  ['cool', 'uncool'],
  ['artistic', 'scientific'],
  ['visible', 'invisible'],
  ['outsider', 'insider'],
  ['dull', 'sharp'],
  ['squishy', 'firm'],
  ['fast', 'slow'],
  ['fishy', 'unassuming'],
  ['fair', 'unfair'],
  ['stumbles', 'soars'],
  ['blooming', 'decaying'],
  ['sweet', 'salty'],
  ['sunny', 'snowy'],
  ['fluorescent', 'pastel'],
  ['moon', 'sun'],
  ['lover', 'fighter'],
  ['vampire', 'zombie'],
  ['expensive', 'cheap'],
  ['wacky', 'calm'],
  ['boss', 'minion'],
  ['ninja', 'monk'],
  ['absorbent', 'repellant'],
  ['duck', 'not a duck'],
  ['bizarro', 'normal'],
  ['wine', 'beer'],
  ['persnickety', 'pleasant'],
  ['serendipity', 'misfortune'],
  ['climbs', 'crawls'],
  ['cooks', 'eats'],
  ['scrooge', 'philanthropist'],
  ['lollygags', 'focuses'],
  ['cheers', 'criticizes'],
  ['agitator', 'peacemaker'],
  ['upstairs', 'downstairs'],
  ['indulgent', 'straight-laced'],
  ['sudden', 'gradual'],
  ['scarred', 'unblemished'],
  ['boink', 'bonk'],
  ['zealous', 'uncertain'],
  ['laughs', 'cries'],
  ['chomps', 'licks'],
  ['ringmaster', 'carnival worker'],
  ['elephant', 'mouse'],
  ['literate', 'numerate'],
  ['paper', 'plastic'],
  ['cash', 'credit'],
  ['student', 'teacher'],
  ['apples', 'oranges'],
  ['alien', 'dinosaur'],
  ['messy', 'clean'],
  ['physical', 'intellectual'],
  ['metallic', 'glassy'],
  ['stands', 'jumps'],
]
